plants = [{
    'Name': "Wirselkraut",
    'Gebiet': "ganz Aventurien",
    'Verbreitung': "Steppen (häufig), Grasländer (gelegentlich)",
    'Bestimmung': "+5",
    'Ernte': "jede Zeit außer Winter",
    'Grundmenge': "W6+4 Blätter",
    'Wirkung': "Unbehandeltes Wirselkraut auf einer Wunde aufgelegt, stoppt die Blutung und bringt im Laufe eines Tages 5 LeP zurück, eingenommen jedoch nur 3 LeP. Zwerge können das Kraut überhaupt nur mit einer gelungenen SelbstbeherrschungsProbe +6 zu sich nehmen – und auch dann können sowohl bei äußerlicher wie auch innerer Anwendung nur 2 LeP zurückgewonnen werden.",
    'Haltbarkeit': "2W6+18 Stunden",
    'Preis': "1D"
}, {
    'Name': "Zwölfblatt",
    'Gebiet': "ganz Aventurien südlich von Riva",
    'Verbreitung': "Wald (gelegentlich), Steppe (gelegentlich), Grasland (selten), Hochland (sehr selten), südliche Sümpfe (sehr selten)",
    'Bestimmung': "+5",
    'Ernte': "Hesinde bis Praios",
    'Grundmenge': "12 Stängel pro Pflanze",
    'Wirkung': " Der Verzehr von frischem Zwölfblatt gewährt für vier Tage Schutz vor Ansteckungen aller Art.",
    'Haltbarkeit': "W6+9 Stunden",
    'Preis': "9S",
    'Besonderheit': "Genuss von frischem Zwölfblatt in der Zeit von Rondra bis Boron führt über kurzfristige, schmerzhafte Magenkrämpfe (2–3 SR) bisweilen zu akuter Atemnot (W6 SP, vorüber- gehende AuP-Einbußen nach Gutdünken des Meisters), die bis zu einer Stunde anhalten kann. Außer bei Erbrechen bedeutet dies jedoch keine Einschränkung der Wirkung.",
}, {
    'Name': "Alraune",
    'Gebiet': " ganz Aventurien nördlich der Khômwüste",
    'Verbreitung': "Waldgebiete (selten), feuchte Grasländer (selten)",
    'Bestimmung': "+9",
    'Ernte': "ganzjährig",
    'Grundmenge': "eine Pflanze",
    'Wirkung': " Der Saft einer Wurzel enthält giftige Bitterstoffe (1W SP), die zu starkem Brechreiz führen (KK –1, GE –1 für W6 SR).",
    'Haltbarkeit': " W3+2 Tage",
    'Preis': "1S",
    'Besonderheit': " Aus Alraune wird das Waffengift Mandragora hergestellt",
}, {
    'Name': "Arganstrauch",
    'Gebiet': "Wälder um Regengebirge, Mysobgebiet, Waldinseln",
    'Verbreitung': " Regenwald (gelegentlich), Sumpf (selten), feuchte Waldgebiete (sehr selten)",
    'Bestimmung': "+4",
    'Ernte': "ganzjährig",
    'Grundmenge': "eine Wurzel",
    'Wirkung': " Die Wurzel gibt 1W6+10 LeP über 7 Stunden Ruhe zurück. Unternimmt man in diesem Zeitraum große Anstrengungen (z.B. Kämpfe oder Gewaltmärsche), bekommt der Patient nur W6 LeP. Beim Wundfieberwurf (siehe GA 208) werden 4 Punkte abgezogen. Wird im Lauf der 7 Stunden eine weitere Wurzel eingenommen, wirkt diese ebenfalls heilkräftig, lähmt aber alle Glieder (für einen Tag GE, FF, KK je –5).",
    'Haltbarkeit': "2W6+18 Stunden",
    'Preis': "7S",
    'Alchimie': "Substitut und Bestandteil der Heiltränke in Südaventurien",
}, {
    'Name': "Atan-Kiefer",
    'Gebiet': "Ehernes Schwert",
    'Verbreitung': "Gebirgshöhen (selten)",
    'Bestimmung': "+6",
    'Ernte': "ganzjährig",
    'Grundmenge': " W20 Stein Rinde, bei komplettem Abschälen verdreifacht sich der Wert.",
    'Wirkung': "keine, die Rinde muss verarbeitet werden.",
    'Haltbarkeit': " W6+14 Tage",
    'Preis': "12S pro Stein"
}, {
    'Name': "Axorda-Baum",
    'Gebiet': "Maraskan",
    'Verbreitung': " Regenwald, Gebirge (beide sehr selten)",
    'Bestimmung': "+4",
    'Ernte': "ganzjährig",
    'Grundmenge': "ein Baum",
    'Wirkung': "unverarbeitet keine",
    'Haltbarkeit': "W6+4 Wochen",
    'Preis': "15 D für ein Drittel der gesamten Baumrinde (etwa 70 Stein)"
}, {
    'Name': "Belmart",
    'Gebiet': " ganz Aventurien nördlich der Linie Grangor–Elburum",
    'Verbreitung': " Wald (gelegentlich), Waldränder (selten)",
    'Bestimmung': "+6",
    'Ernte': " Peraine bis Boron",
    'Grundmenge': "4W20 Blätter",
    'Wirkung': "Die Wirkung von Krankheiten wird für einen Tag aufgehoben, die Krankheit aber nicht geheilt. Wird Belmart bei Vergiftungen eingenommen, so kann der Vergiftete die KO-Probe zum Widerstand gegen das Gift wiederholen (siehe GA 211).",
    'Haltbarkeit': "2W6+18 Stunden",
    'Preis': "9S pro Blatt"
}, {
    'Name': "Chonchinis",
    'Gebiet': " Mittelaventurien von Garetien bis zu den Echsensümpfen",
    'Verbreitung': " Steppe (gelegentlich), Waldränder (selten), Hochland (sehr selten)",
    'Bestimmung': "+6",
    'Ernte': "von Tsa bis Boron, vor allem im Efferd, da sie dann die größte Menge der heilkräftigen Milch enthalten.",
    'Grundmenge': "W20 Blätter",
    'Wirkung': "5 Blätter einer Chonchinis-Pflanze bringen, auf Ätz- oder Brandwunden aufgelegt, insgesamt 5 LeP zurück und betäuben die Wunde so, dass fast kein Schmerz mehr verspürt wird.",
    'Haltbarkeit': "W6+24 Stunden",
    'Preis': "4 S pro 5 Blätter"
}, {
    'Name': "Donf",
    'Gebiet': "ganz Aventurien südlich von Gerasim",
    'Verbreitung': "Sumpf (gelegentlich), Seeufer (selten), Flussauen (sehr selten)",
    'Bestimmung': "+6",
    'Ernte': "ganzjährig",
    'Grundmenge': "ein Stängel",
    'Wirkung': "Die möglichst frisch gekauten Stängel lindern verschiedene Fieber-Krankheiten, insbesondere Paralyse und Brabaker Schweiß. Ihr Schadenswurf wird um 2 gemindert.",
    'Haltbarkeit': " W6+6 Stunden",
    'Preis': "3S",
    'Besonderheit': " Die Gefahr, bei der Ernte in ein von Donf überwuchertes Sumpfloch zu geraten, ist recht groß. Regeln für die Fortbewegung im Sumpf finden Sie in der Geographia Aventurica auf Seite 121."
}, {
    'Name': "Feuerschlick",
    'Gebiet': "Küste um die Elburische Halbinsel",
    'Verbreitung': " Gezeitenzone (häufig; Rondra und Efferd: sehr häufig), Meer (sehr selten)",
    'Bestimmung': "+6 / –5 wenn leuchtend",
    'Ernte': "ganzjährig / Rondra und Efferd",
    'Grundmenge': " W6 Stein der Algen",
    'Wirkung': " Eine Unze der Algen, im nicht leuchtenden Zustand frisch genossen, erleichtert für 1 Stunde Zauber mit dem Merkmalen Hellsicht und Verständigung sowie Proben auf Wissenstalente um 3 Punkte. Eine Unze der leuchtenden Algen, frisch genossen, steigert zwar die Klugheit um 1 Punkt, erleichtert Zauber mit den Merkmalen Hellsicht und Verständigung sowie Proben auf Wissenstalente um 5 Punkte, steigert eine Regeneration um 1 LeP und 1W6 AsP, führt aber für die Dauer der Nacht zu starken Visionen. Um den übel schmeckenden frischen Schlick überhaupt zu sich nehmen zu können, ist eine Selbstbeherrschungs-Probe +7 erforderlich.",
    'Haltbarkeit': "24 Stunden",
    'Preis': "1H pro Stein",
    'Besonderheit': "Schon die Ernte der Algen ist nicht ganz einfach, denn es gilt, den schleimigen, grünen Belag vom Schlick zu trennen. Bei ständiger Einnahme besteht die Gefahr der Ilaris-Sucht (s.u.)."
}, {
    'Name': "Finage",
    'Gebiet': "Südaventurien ab der Linie Neetha–Thalusa",
    'Verbreitung': " Wald und Regenwald (selten), Grasland (sehr selten)",
    'Bestimmung': "+5",
    'Ernte': " Triebe im Peraine, Bast in Boron bis Firun",
    'Grundmenge': "ein Baum mit W20 Trieben",
    'Wirkung': " Der Sud aus 7 Trieben hebt eine beliebige Gute Eigenschaft bzw. senkt eine Schlechte Eigenschaft (Ausnahme: Jähzorn) wieder auf ihren Grundwert, falls die Veränderung durch Gift, Zauberei, Erschöpfung oder ähnliches zustande gekommen ist. Bei häufiger Einnahme von Finage (mehr als dreimal in 9 Tagen) kann der Sud bei gleichbleibender Wirkung zu einer erhöhten Reizbarkeit führen. Der Meister überprüft das, indem er ein W20 rollt. Bei 19–20 steigt der Jähzorn des Behandelten für 9 Tage um 2W6 (bzw. er erwirbt für diese Zeit den gleichnamigen Nachteil).",
    'Haltbarkeit': " W3+3 Monate, versetzt mit Orazal doppelt so lang",
    'Preis': "6S pro 7 Triebe",
    'Alchimie': " zahlreiche Verwendung als Zutat in alchimistischen Tränken wie den Elixieren der Tugenden (SRD 90)"
}, {
    'Name': "Hiradwurz",
    'Gebiet': "Amhalassih, Mhanadistan, Gorien, Aranien",
    'Verbreitung': "Steppe (selten)",
    'Bestimmung': "+8 (Trockenzeit), +5 (Regenzeit)",
    'Ernte': "ganzjährig",
    'Grundmenge': "eine Wurzel",
    'Wirkung': "hebt die Wirkung aller natürlichen und verarbeiteten Schlangengifte auf und gibt nach der Einnahme jede Spielrunde einen durch Schlangengift verlorenen LeP zurück. Es können doppelt soviel LeP zurückgewonnen werden, wie bei einer Probe auf Heilkunde Gift an Talentpunkten übrig bleiben, maximal jedoch 15 LeP pro Wurzel. Wird Hiradwurz bei anderen Vergiftungen verwendet, entscheidet der W20: 1–2: Glück gehabt, die Hiradwurz wirkt wie gehabt; 3–7: keine Wirkung; 8–14: 1W6 zusätzliche SP durch Krämpfe; 15–18: 2W6+2 zusätzliche SP; 19–20: die Giftwirkung ist verdoppelt. Ob ein Held weiß, dass Hiradwurz nur bei Schlangengift zu verabreichen ist, hängt von seiner Herkunft, seinem Pflanzenkunde-Wert und natürlich vom Meister ab. Wird öfter eine Wurzel eingenommen (mindestens fünfmal im Monat), so erleidet man für 3 Monate bei jeder Vergiftung mit Schlangengift nur 70 % des üblichen Schadens.",
    'Haltbarkeit': "W3+6 Tage",
    'Preis': "8S",
    'Alchimie': "sinnvolles Substitut für Belmart"
}, {
    'Name': "Hollbeere",
    'Gebiet': "Albernia und Nostria",
    'Verbreitung': "Waldränder (häufig), Wald (gelegentlich)",
    'Bestimmung': "+4",
    'Ernte': "Rondra und Efferd",
    'Grundmenge': "2W6 Sträucher mit jeweils 2W6+5 Beeren und 2W6+3 Blättern der untersten Zweige",
    'Wirkung': "Die Beeren sind unverarbeitet leicht giftig (Brechreiz und keine nächtliche Regeneration), vergoren ergeben sie ein wirksames Brechmittel. Die Blätter besitzen roh keine Wirkung.",
    'Haltbarkeit': "W6 Tage",
    'Preis': ""
}, {
    'Name': "Joruga",
    'Gebiet': ": Nostria, Andergast, Albernia und Nordmarken",
    'Verbreitung': " Wald (gelegentlich), Wiesen (selten), Gebirge (sehr selten)",
    'Bestimmung': "+7",
    'Ernte': " Rahja bis Boron",
    'Grundmenge': "eine Wurzel",
    'Wirkung': "Die unbehandelte Wurzel ist unverdaulich und wird unter starkem Durchfall wieder ausgeschieden.",
    'Haltbarkeit': "W3+2 Tage",
    'Preis': "8S"
}, {
    'Name': "Klippenzahn",
    'Gebiet': "Orkland, Gjalsker Öden, Thorwal",
    'Verbreitung': "Gebirge (gelegentlich), Hochland (gelegentlich)",
    'Bestimmung': "+8",
    'Ernte': "Peraine bis Rondra",
    'Grundmenge': "2W6 Stängel",
    'Wirkung': "Der ausgepresste Saft eines Stängels stärkt die Lebenskraft und beschleunigt die Wundheilung (je +1/2 LeP, maximal 10 Stängel nutzbar). Außerdem ist die Erkrankungswahrscheinlichkeit für Wundfieber um 20 % vermindert, wenn der Saft unmittelbar nach der Verwundung eingenommen wurde. Neben der inneren Anwendung empfiehlt sich ebenso ein Tränken des Verbandes mit dem Saft, denn er wirkt auch schmerzlindernd. Hierbei ist die Größe der Wunde zu beachten – zur Regeneration von 1 SP werden hier etwa 3 Stängel benötigt. Spieltechnische Wunden benötigen, so behandelt, für ihre Heilung nur noch zwei Drittel der Zeit.",
    'Haltbarkeit': " W3+2 Tage, maximal bis zum nächsten Vollmond",
    'Preis': " 5H pro Stängel"
}, {
    'Name': "Lulanie",
    'Gebiet': "ganz Mittelaventurien zwischen Trallop und Punin",
    'Verbreitung': " Wald (selten), Waldränder (sehr selten)",
    'Bestimmung': "+5",
    'Ernte': "Rahja bis Rondra",
    'Grundmenge': "eine Blüte",
    'Wirkung': " Die roh verzehrten Blüten schmecken nicht sonderlich gut und bewirken nichts, im Tee aufgegossen beruhigen sie jedoch Magen und Nerven. Magenverstimmungen durch schwer verdauliche Pflanzen können auf diese Art beispielsweise geheilt werden, ebenso Tobsuchtsanfälle in Folge einer gelungenen Jähzorn-Probe.",
    'Haltbarkeit': "W3+5 Tage",
    'Preis': "12S"
}, {
    'Name': "Nothilf",
    'Gebiet': "Wälder um die Salamandersteine",
    'Verbreitung': " Wald, Gebirge (jeweils selten)",
    'Bestimmung': "+6",
    'Ernte': "Blüten im Praios; Blätter im Peraine",
    'Grundmenge': "W20+2 Blüten, 2W20 +10 Blätter",
    'Wirkung': " Nothilf muss weiterverarbeitet werden, der Genuss der rohen Pflanze ist absolut wirkungslos. Werden Brandwunden mit frisch gepflückten Nothilfblättern versorgt, so ist eine Probe auf Heilkunde Wunden um 5 erleichtert.",
    'Haltbarkeit': " W3+3 Tage (Blüte oder Blätter)",
    'Preis': " 3 D (je Blüte), 4 D (je 3 Blätter)"
}, {
    'Name': "Olginwurz",
    'Gebiet': "Raschtulswall",
    'Verbreitung': "Hochland, Gebirge, Wald (jeweils selten)",
    'Bestimmung': "+10",
    'Ernte': "ganzjährig",
    'Grundmenge': "W3 Moosballen",
    'Wirkung': "Eine mit etwas Alkohol eingenommene (und gut zerkaute) Olginwurz kann unterstützend zur Entgiftung des Körpers eingesetzt werden. Pro Portion sinkt die Giftstufe aller Gifte bis zur Stufe 19 um einen Punkt (maximal jedoch auf die halbe Giftstufe), zudem wird nach Einnahme von mindestens zwei Portionen während der nächsten Stunde jeder Schadenswurf durch das Gift um 1 Punkt vermindert (allerdings kann dieser Effekt durch Mehreinnahme nicht erhöht werden). Alle Proben-Erschwernisse auf Heilkunde Gift sind um die Anzahl der eingenommenen Moosballen reduziert (maximal jedoch um die halbe Giftstufe).",
    'Haltbarkeit': "2W6+12 Stunden",
    'Preis': ": 3 D pro Moosballen"
}, {
    'Name': "Rote Pfeilblüte",
    'Gebiet': "ganz Südaventurien südlich der Linie Neetha–Thalusa",
    'Verbreitung': "Küstensümpfe, Regenwald (jeweils gelegentlich), Wald (sehr selten)",
    'Bestimmung': "+7",
    'Ernte': "Peraine bis Rahja",
    'Grundmenge': "W6 Blüten",
    'Wirkung': " Drei Blüten werden zu einem Tee aufgegossen, der 3W6+2 LeP binnen drei Stunden bringt. Eine Zugabe weiterer Blüten zum Tee bewirkt nichts, wenn man davon absieht, dass das liebliche Getränk dadurch bitter wird.",
    'Haltbarkeit': "W6 Stunden",
    'Preis': "1 S pro Blütte",
    'Besonderheit': "Roh genossen bringen die Blütenknospen CH +1 für 12 Stunden."
}, {
    'Name': "Roter Drachenschlund",
    'Gebiet': "ganz Aventurien nördlich einer Linie Drôl–Thalusa",
    'Verbreitung': " Waldränder, Flussufer (jeweils sehr selten)",
    'Bestimmung': "+10 (+3 zur Blütezeit)",
    'Ernte': "ganzjährig (Blüte im Ingerimm und Rahja)",
    'Grundmenge': " W6 Blätter",
    'Wirkung': " Das Gewächs kann den Ausbruch von Lykanthropie verhindern. Dazu muss dem Opfern ein Verband aus frischen Drachenschlund-Blättern auf die (nötigenfalls aufgeschnittene) Bisswunde gelegt werden. Eine Behandlung mit dieser Pflanze wirkt bei einem Werwolfsopfer nur ein einziges Mal, und nur dann, wenn es nicht bereits zu einer Verwandlung gekommen ist.",
    'Haltbarkeit': "W3+6 Tage",
    'Preis': "20D",
    'Alchimie': " obskure Experimente in Verwandlungselixieren und alchimistischen Fluchbrechern, doch wahrscheinlich bisher ohne Erfolg.",
    'Besonderheit': " Jeder Versuch des kultivierten Anbaus – sogar mittels Peraineliturgien – ist rätselhafterweise fehlgeschlagen. Der Anblick der geöffneten Blüte erzeugt ein mulmiges Gefühl, oftmals glauben sich Betrachter von der Pflanze beobachtet."
}, {
    'Name': "Tarnele",
    'Gebiet': "ganz Aventurien zwischen Gerasim und Mengbilla",
    'Verbreitung': " Wiesen (häufig), Flussauen (häufig), Wald (gelegentlich), Sumpf (gelegentlich), Hochland (sehr selten)",
    'Bestimmung': "+4",
    'Ernte': "Ingerimm bis Travia",
    'Grundmenge': "ganze Pflanze",
    'Wirkung': "Auf Wunden aufgetragen, wirkt der Pflanzenbrei schmerzlindernd und heilkräftig: Zur nächtlichen Regeneration darf ein weiterer Lebenspunkt hinzuaddiert werden. Ohne weitergehende Bearbeitung verlieren die pflanzlichen Wirkstoffe innerhalb eines Tages ihre Heilkraft.",
    'Haltbarkeit': " W6+18 Stunden",
    'Preis': "4 H"
}, {
    'Name': "Traschbart",
    'Gebiet': "Steineichenwald, Finsterkamm, Koschberge und Eisenwald",
    'Verbreitung': " Wald (häufig), Sumpfgebiete (gelegentlich)",
    'Bestimmung': "+6",
    'Ernte': "ganzjährig",
    'Grundmenge': "W6 Flechten",
    'Wirkung': " wirksames Mittel gegen fiebrige Erkrankungen (siehe unten), frisch jedoch mit ekelerregendem Geschmack. Daher wird es fast immer getrocknet.",
    'Haltbarkeit': "bei feuchter Lagerung 1W6 Tage",
    'Preis': "1H pro Flechte"
}, {
    'Name': "Ulmenwürger",
    'Gebiet': "ganz Aventurien nördlich einer Linie Havena–Perricum",
    'Verbreitung': "Wald (gelegentlich), Waldrand (selten)",
    'Bestimmung': "+2",
    'Ernte': "Efferd bis Travia",
    'Grundmenge': "W20 Blüten",
    'Wirkung': "Ein Aufguss aus 12 Blüten des Ulmenwürgers verbessert die nächtliche Regeneration um 2 LeP und senkt die Gefahr der Ansteckung durch Wundfieber für einen Tag um 20 %. Werden frische Blüten verwendet, schmeckt der Aufguss leicht seifig.",
    'Haltbarkeit': "siehe unten",
    'Preis': "6S"
}, {
    'Name': "Vierblättrige Einbeere",
    'Gebiet': "ganz Aventurien nördlich des Yaquir",
    'Verbreitung': "Waldränder (häufig), Wald (häufig), Grasland (gelegentlich), sonstiges Gelände (sehr selten)",
    'Bestimmung': "+5",
    'Ernte': "von Phex bis Hesinde",
    'Grundmenge': "Strauch mit 1W6 Beeren",
    'Wirkung': "Die Beere stoppt Blutungen und bringt W3 LeP zurück, bei einer gelungenen Heilkunde-Probe (Gift, Krankheiten oder Wunden) sogar zusätzliche W6 LeP. Auch bei der Anwendung mehrerer Beeren kann der Behandelte maximal W6 LeP pro Stunde durch Einbeeren zurückbekommen; unternimmt er in dieser Zeit Anstrengungen, bringt jede Beere nur noch 1 LeP zurück.",
    'Haltbarkeit': "W3+2 Tage",
    'Preis': "4S",
    'Besonderheit': " Werden an einem Tag 4 Beeren eingenommen, besteht bei 1–4 auf W20 die Möglichkeit einer Sucht (Krankheit Stufe 10), die mit jeder weiteren Beere um 5 % steigt. Ein Süchtiger, der nicht einmal in der Woche Vierblatt zu sich nehmen kann, verliert 1W6 LeP. Vierblatt hat für ihn keine heilsame Wirkung mehr."
},
#     {
#     'Name': "",
#     'Gebiet': "",
#     'Verbreitung': "",
#     'Bestimmung': "",
#     'Ernte': "",
#     'Grundmenge': "",
#     'Wirkung': "",
#     'Haltbarkeit': "",
#     'Preis': ""
# },
]

alchimic = [{
    'Name': "",
    'Gruppe': "",
    'Beschaffung': "",
    'Rezeptur': "",
    'Labor': "",
    'Probe': "",
    'Wirkung': {
        'M': "",
        'A': "",
        'B': "",
        'C': "",
        'D': "",
        'E': "",
        'F': "",
    },
    'Verbreitung': "",

}]